# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce1ccc166a25daaa483e783eaca1a6ca66d1f35a5425f463e506e4b56fb218544a23bcd6ad72630b8a61765b3c57d99aa22b0355562df1f1a4a044a0ae27b401

test:
  secret_key_base: 4fe1032df8f456f1d1bf19f05ef7dfd478acf38b9c38f513ded0db2abd84526147f67cf820b0a3554f53ec84df2c830bb54a58181baadee555dbf41df4f870ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
